### ISSUE TITLE
Stuck at Enable WETH

### ISSUE THREAD

**Issue by Jay1567** [compound-finance/compound-money-market#2]
Hey  why its again trying to wrap eth

i tried to speed up the transaction so wrap was done with different transasction hash but still the wrap was done
What should I Do??

The successful WETH conversation hash is:- 0x43b028200f47fce9885940fe2bc835edc9b17f125f42f28d39acbd25cc5e8abe

![screenshot 2018-09-29 at 4 20 38 pm](https://user-images.githubusercontent.com/43697256/46246376-0c56a980-c41a-11e8-96ef-a9da1d179e52.png)

**Comment by hayesgm** [comment]
@Jay1567 It looks like you wrapped 0.2 ether with [this transaction](https://etherscan.io/tx/0xc6e8f8f96a51408aa0c740bb1a909424074e1bd0e98364e06aa91cff0fc91f52) and you approved WETH with Compound with [this transaction](https://etherscan.io/tx/0x43b028200f47fce9885940fe2bc835edc9b17f125f42f28d39acbd25cc5e8abe). Are you still seeing this issue? The dApp should function correctly in this case.

**Comment by Jay1567** [comment]
Yes you are right @hayesgm .
But it shows the same like previous image and tells me to enable it again. When I Click on the Recent Activity's Enable WETH it opens this page 
![screenshot 2018-09-30 at 8 44 45 am](https://user-images.githubusercontent.com/43697256/46252895-1bc30a80-c48d-11e8-89d1-ef56d99698ab.png)

What should I do??

**Comment by Jay1567** [comment]
Hey I tried to Enable WETH again and the transaction did successfully completed but it is still is not reflecting in the compound. Even if you click on the new enable WETH it shows success.

Transaction:- 0x3de7889184bc4445fd49466982154f9a4e6e3adc9a21f9088ff3199b1afa7425

![screenshot 2018-09-30 at 4 19 43 pm](https://user-images.githubusercontent.com/43697256/46256781-0241b300-c4cd-11e8-8bea-faf10b45a138.png)

![screenshot 2018-09-30 at 4 18 36 pm](https://user-images.githubusercontent.com/43697256/46256784-0ec60b80-c4cd-11e8-9315-b3f8c33c7df6.png)

**Comment by torreyatcitty** [comment]
@Jay1567 I can see you successfully supply 0.2 Wrapped Ether to Compound with this [transaction](https://etherscan.io/tx/0xc8e312a179fb73b91e6efe3e4e48ba2e218d09db746429d9913345463556784d).

Also, I can see your current supply balance with interest by reading from the contract directly as shown here:

<img width="546" alt="screen shot 2018-10-11 at 12 16 31 am" src="https://user-images.githubusercontent.com/10445874/46786858-fafb8000-ccea-11e8-8c71-29eade4a54aa.png">

From both of those I know that your Wrapped Ether is supplied to the Protocol and earning interest. I would recommend restarting your browser to see if that helps as sometimes we have observed Metamask having issues.

**Comment by torreyatcitty** [comment]
We have made several improvements to help with this issue so I'm going to close for now.
