### ISSUE TITLE
Repo for API? Repo for website?

### ISSUE THREAD

**Issue by fulldecent** [compound-finance/compound-money-market#3]
Is the code for the API service (api.compound.finance) intended to be public? Could you please point me to the repo?

Is the code for the frontend website intended to be public? Same question.

A failure to properly document something on the website or a failure to properly respond to an API request could lead to a security vulnerability for a user.

**Comment by torreyatcitty** [comment]
The codebase for the API and frontend are not intended to be public at this time. The API is primarily used to provide historical data and other information to developers building on Compound. We will be sure to inform the community if we decide to make our other repos public.
